language: scala
scala:
   - 2.12.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION run

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/website/
  repo: wayfarerx/wayfarerx.github.io
  target_branch: master
  fqdn: wayfarerx.net
  on:
    branch: master

after_deploy:
  - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/e5b7e3a58848fdda2a17bacc7ce1bb62/purge_cache" -H "X-Auth-Email: x@wayfarerx.net" -H "X-Auth-Key: $CLOUDFLARE_TOKEN" -H "Content-Type: application/json" --data '{"purge_everything":true}'