language: scala
scala:
   - 2.12.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION run

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/website/
  repo: wayfarerx/wayfarerx.github.io
  target_branch: master
  fqdn: wayfarerx.net
  on:
    branch: master

after_deploy:
  - chmod +x ./bin/purge.sh
  - ./bin/purge.sh $CLOUDFLARE_TOKEN