language: scala
scala:
   - 2.12.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION run

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/website/
  repo: wayfarerx.github.io
  target_branch: master
  fqdn: wayfarerx.net
  on:
    branch: master